# Generated by Django 3.2.10 on 2022-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='email',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
