# Generated by Django 3.2.10 on 2022-06-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0003_remove_auditorium_generator'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditorium_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('generator', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templeapp.user')),
            ],
        ),
    ]
