# Generated by Django 3.2.10 on 2022-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0004_auditorium_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitti',
            name='no_members',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chitti',
            name='total_amounts',
            field=models.BigIntegerField(default=22),
            preserve_default=False,
        ),
    ]
