# Generated by Django 3.2.10 on 2022-07-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0006_chitti_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitti_details',
            name='time',
        ),
        migrations.RemoveField(
            model_name='chitti_details',
            name='type',
        ),
    ]
