# Generated by Django 3.2.10 on 2022-07-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0007_auto_20220705_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chitti_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templeapp.chitti')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templeapp.members')),
            ],
        ),
    ]
