# Generated by Django 3.2.10 on 2022-07-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0011_remove_auditorium_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitti',
            old_name='amounts',
            new_name='chitti_amount',
        ),
        migrations.RenameField(
            model_name='chitti',
            old_name='total_amounts',
            new_name='winning_amounts',
        ),
    ]
