# Generated by Django 4.0.6 on 2022-07-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0014_chitti_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user_id',
        ),
    ]
