# Generated by Django 4.0.6 on 2022-07-24 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0015_remove_bank_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitti_payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='chitti_payment',
            name='datetime',
        ),
        migrations.AddField(
            model_name='chitti_payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
