# Generated by Django 3.2.10 on 2022-08-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0017_chitti_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='committe_program',
            name='committee_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='templeapp.committee'),
            preserve_default=False,
        ),
    ]
